# Generated by Django 5.2 on 2025-11-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='сore_post',
        ),
    ]
