# Generated by Django 5.2 on 2025-11-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_post", "0001_initial"),
        ("core_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="post_liked",
            field=models.ManyToManyField(related_name="liked_by", to="core_post.post"),
        ),
    ]
