# Generated by Django 5.2 on 2025-12-21 16:06

from django.db import migrations, models

import core.user.models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0004_user_comments_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.user.models.user_directory_path
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_seed",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DiceBear seed для стиля 'dylan'",
                max_length=100,
            ),
        ),
    ]
