# Generated by Django 5.2 on 2025-12-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0005_user_avatar_user_avatar_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
