# Generated by Django 5.2 on 2025-12-30 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0006_user_is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="post_liked",
            new_name="posts_liked",
        ),
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "followed",
                    models.ForeignKey(
                        help_text="Who is being subscribed to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Who is subscribing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "followed"],
                        name="core_user_u_user_id_72d074_idx",
                    ),
                    models.Index(
                        fields=["followed"], name="core_user_u_followe_211b86_idx"
                    ),
                ],
                "unique_together": {("user", "followed")},
            },
        ),
    ]
