# Generated by Django 5.2 on 2026-01-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_comment", "0001_initial"),
        ("core_user", "0007_rename_post_liked_user_posts_liked_userfollow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_seed",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DiceBear seed for style 'dylan'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="comments_liked",
            field=models.ManyToManyField(
                related_name="liked_by", to="core_comment.comment"
            ),
        ),
    ]
